{% set name = "microsoft-kiota-serialization-text" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_serialization_text-{{ version }}.tar.gz
  sha256: 4289508ebac0cefdc4fa21c545051769a9409913972355ccda9116b647f978f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
    - wheel
  run:
    - python
    - microsoft-kiota-abstractions

test:
  imports:
    - kiota_serialization_text
  commands:
    # disable pip check temporarily because of https://github.com/conda-forge/python-dateutil-feedstock/issues/29
    #- pip check
  requires:
    - python
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/serialization/text
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-python/tree/main/packages/serialization/text
  doc_url: https://github.com/microsoft/kiota-python/blob/main/packages/serialization/text/README.md


extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/64252
    reason: Dependency for msgraph-sdk
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - xylar

